DROP DATABASE IF EXISTS CAPSTONE;

CREATE DATABASE CAPSTONE;

USE CAPSTONE;

CREATE TABLE users (
  user_id INT(25) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(70) NOT NULL,
  password VARCHAR(255) NOT NULL,
  user_email  VARCHAR(255)  NOT NULL,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_alumni BOOLEAN NOT NULL DEFAULT FALSE
);